spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolDb
    username: root
    password: Kigali@8160

  jpa:
    hibernate:
      ddl-auto: update



#
#  spring.datasource.url=jdbc:mysql://localhost:3306/schoolDb
#spring.datasource.username=root
#spring.datasource.password=Kigali@8160
#spring.jpa.hibernate.ddl-auto=update